### ISSUE TITLE
Node 16 is deprecated

### ISSUE THREAD

**Issue by TheTumultuousUnicornOfDarkness** [hummeltech/freebsd-vagrant-action#2]
Hello,

When I use hummeltech/freebsd-vagrant-action@v1.4, I have this warning:
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/cache@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

Could you please update to actions/cache@v4?

**Comment by hummeltech** [comment]
Thanks for the report @TheTumultuousUnicornOfDarkness, a new version [v1.5](https://github.com/hummeltech/freebsd-vagrant-action/releases/tag/v1.5) has been released
